### ISSUE TITLE
Es necesario actualizar el badge de codecov

### ISSUE THREAD

**Issue by RodriguezNazareno56** [RodriguezNazareno56/FIUBA-Algo3-TP2#2]
Este es el badge para el README.md
[![codecov](https://codecov.io/gh/RodriguezNazareno56/FIUBA-Algo3-TP2/graph/badge.svg?token=A6M4WZMIMN)](https://codecov.io/gh/RodriguezNazareno56/FIUBA-Algo3-TP2)
`[![codecov](https://codecov.io/gh/RodriguezNazareno56/FIUBA-Algo3-TP2/graph/badge.svg?token=A6M4WZMIMN)](https://codecov.io/gh/RodriguezNazareno56/FIUBA-Algo3-TP2)`

Hasta donde entiendo tambien debemos modificar el build.yml de:
```
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      ...
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
```

a

```
name: build
on: [ push, pull_request ]
jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      ...
      - name: Upload coverage report
        uses: codecov/codecov-action@v2
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```
